name: Update News

on:
  schedule:
    - cron: - cron: "*/2 * * * *" # רץ כל שעה עגולה
  workflow_dispatch: # מאפשר להריץ ידנית לבדיקה

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "Update news" || exit 0
          git push
